@baseURL = http://localhost:5050/type 



### GET ALL TYPES
GET {{baseURL}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQwMmQ5Zjc2ZjQ3M2Y0YTU0ZDQ1ZTciLCJwaG9uZV9udW1iZXIiOiI5MDAwNzA3NzAiLCJwYXNzd29yZCI6IiQyYiQxMCRYY3ZKZnJnLkR0L2J5Z1FMUS5RcEIuOXhsNmUxQk5FcVd6QlFWQlpmSHVDcmNHS1g3aENLZSIsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfZGVsZXRlZCI6ZmFsc2UsInJvbGUiOiI2NDNkZjFmNDFiYzA5NjYzNjM1NTM2N2MiLCJzdGFmZiI6IjY0NDAyZDlmNzZmNDczZjRhNTRkNDVlNSIsImNyZWF0ZWRBdCI6IjIwMjMtMDQtMTlUMTg6MDY6MjMuNzk3WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMzBUMDI6MTU6NTEuMjQ3WiIsIl9fdiI6MCwiaWF0IjoxNjg1NjI0ODk0fQ.Im8ZkzB4qyymlLMnm-yNVO5_xA-qwpyqH2c2klTSlTw




### CREATE NEW TYPE
POST {{baseURL}}
Content-Type: application/json

{
    "name":"divan"
}